### ISSUE TITLE
Front End Guide Topics

### ISSUE THREAD

**Issue by xtine** [18F/frontend#158]
These are suggested topics for the Front End Guide:
## HTML / Structure
- [ ] HTML style guide (#7)
- [ ] WIP PR (#102)
- [ ] Semantics (#66)
## CSS
- [ ] CSS architecture (#22)
## Testing
- [ ] Frontend testing (#28)
- [ ] JS Unit testing (#29)
- [ ] Regression testing (#30)
## Images
- [ ] SVG (#3)
- [ ] Visual Components (#4)
- [ ] Image Optimization Best Practices (#6)
## JavaScript
- [x] JS Style Guide (#98)
- [ ] JS bundling recommendations (#40)
- [ ] JS framework support (#128)
- [x] Add JS lint recommendation (#156)
## Performance
- [ ] Performance Guide (#53)
## Security
- [ ] Security Tips and Checklist (#172)
## Resources
- [ ] Educational resources (#134)

**Comment by jseppi** [comment]
I checked off the item for #156 since it was closed by https://github.com/18F/frontend/pull/168

**Comment by xtine** [comment]
Adding **Security** as a guide topic.

**Comment by toolness** [comment]
Should the guide have a section on progressive enhancement?  e.g. something similar to [gov.uk's service manual page on progressive enhancement](https://www.gov.uk/service-manual/technology/using-progressive-enhancement)?

**Comment by xtine** [comment]
Closing in favor of a new issue with one that is more focused on user research on how the guide should expand upon.
